name: Build
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    name: Build Solution
    runs-on: windows-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Restore NuGet Packages
        run: msbuild -t:restore src/Bonsai.PulsePal.sln
  
      - name: Build Solution
        run: msbuild src/Bonsai.PulsePal.sln /p:Configuration=Release
